# see https://github.com/Homebrew/homebrew-bundle for documentation

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "sambadevi/powerlevel9k"
tap "thoughtbot/formulae"

brew "azure-cli"
brew "gdbm"
brew "grip"
brew "hstr"
brew "jq"
brew "lsusb"
brew "ncurses"
brew "oniguruma"
brew "openssl@1.1"
brew "pcre"
brew "picocom"
brew "python"
brew "readline"
brew "sqlite"
brew "rcm"
brew "tree"
brew "xz"
brew "zsh"
brew "sambadevi/powerlevel9k/powerlevel9k"

# this currently seems not to be working
# cask_args appdir: "/Applications"

cask "balenaetcher"
cask "docker"
cask "iterm2"
cask "notable"
cask "sourcetree"
cask "sublime-text"
cask "vagrant"
cask "virtualbox"
